[metadata]
name = pycmplot
version = 0.4.3
author = Kevin Esoh
author_email = kesohku1@jh.edu
description = Multi-track circular and linear Manhattan plot generation for GWAS summary statistics

[options]
packages = find:
python_requires = >=3.9
install_requires =
    pandas>=1.5
    numpy>=1.23
    matplotlib>=3.6
    pillow>=9.0
    liftover>=1.4.1
    natsort>=8.0
    adjustText>=0.8
    pyarrow>=23.0.1
    fastparquet>=2025.12.0

[options.packages.find]
exclude = 
    tests*
    dist*
    changelog.d*
    build-pypi-package.md
    pycmplot_python_api.ipynb
    mit-license.txt
    bak
    benchmark
    pycmplot_docs
    docs
    CHANGELOG.rst
    pycmplot_benchmark.ipynb

[options.entry_points]
console_scripts =
    pycmplot = pycmplot._core:main
